name: "Jobs concatenados"

on:
  push:
    branches: ["main"]

jobs:
  first_job:
    name: Load Artifacts
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.github_output.outputs.my_variable }}

    steps:
      - name: Generate file
        run: |
          echo "Bonjour, Je me apple Jhon Galindo, J'ai trente-deux ans et J'adore la programmation" >> test.log

      - name: Load artifact
        uses: actions/upload-artifact@v4
        with:
          name: archivo_pitufina
          path: test.log

  second_job:
    name: Download Artifacts
    runs-on: ubuntu-latest
    needs: first_job

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: archivo_pitufina

      - name: Cat file
        run: cat test.log
